### ISSUE TITLE
Integration 'hilo' not found

### ISSUE THREAD

**Issue by skimaniac** [francispoisson/hilo#14]
après avoir installer la mise à jour de Home Assistant 2021.6.0 j'ai ce message d'erreur: Integration 'hilo' not found.
j'ai essayé de réinstaller hilo, mais je ne peux pas redémarrer HA à cause de l'erreur de config.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:518 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 18:53:23 (2 occurrences) 
Last logged: 18:55:25

[547346727744] The system cannot restart because the configuration is not valid: Component error: hilo - Integration 'hilo' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: hilo - Integration 'hilo' not found.

**Comment by skimaniac** [comment]
je viens de voir ça dans le lot:

2021-06-02 18:06:27 ERROR (SyncWorker_8) [homeassistant.loader] The custom integration 'hilo' does not have a valid version key (['0.1.1']) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by skimaniac** [comment]
finalement j'ai modifié   "version": "0.1.1",  dans le fichier manifeste.json (j'ai enlever [ ] ) et ça fonctionne de nouveau

**Comment by arnaud-42** [comment]
Je confirme ta solution.
C'est ok pour moi maintenant.

**Comment by isbkch** [comment]
Ça a marché pour moi aussi
