### ISSUE TITLE
Request for access token failed

### ISSUE THREAD

**Issue by jeromelefeuvre** [francispoisson/hilo#17]
Salut,

tout marchais bien et j'ai vu ça aujourd'hui dans mes logs. Failed sur le token, tu as deja vu ça ?
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hilo.hiloapi
Source: custom_components/hilo/hiloapi.py:110 
Integration: Hilo HA integration (documentation, issues) 
First occurred: 18:59:15 (1 occurrences) 
Last logged: 18:59:15

Request for access token failed.
```

Vu que le token failed, j'ai une erreur qui en découle:
```
Update for binary_sensor.defi_hilo fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hilo/binary_sensor.py", line 55, in update
    self._h.update()
  File "/config/custom_components/hilo/hiloapi.py", line 245, in update
    self.refreshToken()
  File "/config/custom_components/hilo/hiloapi.py", line 158, in refreshToken
    if time.time() > self.access_token_expiration:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

**Comment by jeromelefeuvre** [comment]
Probleme réglé après un reset du password! Je close le ticket!
