### ISSUE TITLE
Integration failed to load with merge #35

### ISSUE THREAD

**Issue by Fox350** [francispoisson/hilo#36]
Hy guys, I did update from HACS to # 35 and the integration now fail to load.  I will rollback for now.
Here is the error during the setup of component hilo :

Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.setup
Source: custom_components/hilo/hilo_api.py:71
Integration: Hilo HA integration (documentation, issues)
First occurred: 19:58:49 (1 occurrences)
Last logged: 19:58:49

Error during setup of component hilo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/hilo/__init__.py", line 68, in async_setup
    return await _async_process_config(hass, config)
  File "/config/custom_components/hilo/__init__.py", line 90, in _async_process_config
    await hilo.async_update_all_devices()
  File "/config/custom_components/hilo/hilo_api.py", line 213, in async_update_all_devices
    await self.get_devices()
  File "/config/custom_components/hilo/hilo_api.py", line 193, in get_devices
    url = f"{await self.location_url}/Devices"
  File "/config/custom_components/hilo/hilo_api.py", line 57, in location_url
    self._location_id = await self.get_location_id()
  File "/config/custom_components/hilo/hilo_api.py", line 159, in get_location_id
    req = await self._request(url)
  File "/config/custom_components/hilo/hilo_api.py", line 111, in _request
    await self.refresh_token()
  File "/config/custom_components/hilo/hilo_api.py", line 150, in _refresh_token
    self._access_token = await self.get_access_token()
  File "/config/custom_components/hilo/hilo_api.py", line 137, in get_access_token
    req = await self.async_call(url, method="post", headers=headers, data=body)
  File "/config/custom_components/hilo/hilo_api.py", line 95, in async_call
    return await try_again(f"{url} returned {resp.status}")
  File "/config/custom_components/hilo/hilo_api.py", line 73, in try_again
    return await self.async_call(
  File "/config/custom_components/hilo/hilo_api.py", line 95, in async_call
    return await try_again(f"{url} returned {resp.status}")
  File "/config/custom_components/hilo/hilo_api.py", line 73, in try_again
    return await self.async_call(
  File "/config/custom_components/hilo/hilo_api.py", line 95, in async_call
    return await try_again(f"{url} returned {resp.status}")
  File "/config/custom_components/hilo/hilo_api.py", line 73, in try_again
    return await self.async_call(
  File "/config/custom_components/hilo/hilo_api.py", line 95, in async_call
    return await try_again(f"{url} returned {resp.status}")
  File "/config/custom_components/hilo/hilo_api.py", line 71, in try_again
    raise HomeAssistantError("Retry limit reached")
homeassistant.exceptions.HomeAssistantError: Retry limit reached

Also, :
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.hilo.hilo_api
Source: custom_components/hilo/hilo_api.py:70
Integration: Hilo HA integration (documentation, issues)
First occurred: 19:58:49 (1 occurrences)
Last logged: 19:58:49

Unable to post https://hilodirectoryb2c.b2clogin.com/hilodirectoryb2c.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1A_B2C_1_PasswordFlow: https://hilodirectoryb2c.b2clogin.com/hilodirectoryb2c.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1A_B2C_1_PasswordFlow returned 400

**Comment by descha000** [comment]
je confirme que moi aussi, en enlevant les caracteres speciaux de mon mot de passe, ca a réglé le problème.  J'en comprends que Hilo donne l'indication dans l'app d'utiliser 3 des 4 suivants: majuscules, minuscules, special char et chiffres, mais que leur API pour obtenir le token ne manage pas les special chars...
