### ISSUE TITLE
Update for binary_sensor.defi_hilo fails

### ISSUE THREAD

**Issue by skimaniac** [francispoisson/hilo#52]
J'ai cette erreur qui revient tres souvent. mais je ne suis pas capable d'identifier exactement d'où ça vient. je sais pas non plus pourquoi j'ai 2 binary_sensor.defi_hilo je ne trouve rien dans mon fichier configuration.yaml qui y fait référence.

Update for binary_sensor.defi_hilo fails
Update for binary_sensor.defi_hilo_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/hilo/binary_sensor.py", line 37, in _async_update
    self._state = await self.d._h.get_events()
  File "/config/custom_components/hilo/api.py", line 253, in get_events
    start_time = datetime.strptime(r.get("startTimeUTC"), "%Y-%m-%dT%H:%M:%SZ")\
TypeError: strptime() argument 1 must be str, not None

**Comment by skimaniac** [comment]
Ça a corrigé mon problème.
