### ISSUE TITLE
Possible changement ou problème côté Hilo ne venant pas de la maj 

### ISSUE THREAD

**Issue by Fox350** [francispoisson/hilo#53]
Sans avoir effectué la mise à jour j'éprouve des problèmes.  

Bonjour à tous, éprouvez-vous depuis hier la perte de rafraîchissement du compteur sensor.smartenergymeter?  Des fois, je redémarre HA et le sensor est là, des fois non.  Le compteur se met à jour au redémarrage de HA ensuite rien : 
![image](https://user-images.githubusercontent.com/78315589/143502094-e0b381dd-375c-4a01-9cac-15ed4bf0adfa.png)

Avez-vous perdu des entités de power des termostats ou des dispositifs de façon un peu aléatoire entre les redémarrage ?
![image](https://user-images.githubusercontent.com/78315589/143502221-ec03c370-d10a-460c-8d44-0b88b63101db.png)

J'avais fait la maj, je croyais que c'était la cause.  Après avoir fait un rollback autant au niveau du dossier config\custom_components\hilo qu'un full restore de ma VM HA.  

Je crois donc qu'Hilo a changé qqchose avec l'arrivé du premier défi aujourd'hui.  

Suis-je seul sur ma planète ?

Voici mes logs :
Logger: homeassistant.components.sensor
Source: custom_components/hilo/sensor.py:27
Integration: Capteur (documentation, issues)
First occurred: 16:38:20 (2 occurrences)
Last logged: 16:38:20

Error adding entities for domain sensor with platform hilo
Error while setting up hilo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/hilo/sensor.py", line 27, in state
    return str(int(self._get('Power', 0)))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by valleedelisle** [comment]
ouais on dirait qu'hilo nous throttle en retournant un objet vide. Je vais soumettre une patch dans pas trop long.

Merci de l'avoir flaggé.

**Comment by Fox350** [comment]
Merci à toi du suivi !

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
